
#' Read EXIF data
#'
#' Checks for command length, such that windows command length policies are respected.
#'
#' @param filename A vector of filenames (like that generated by \code{list.files(..., full.names=TRUE)})
#' @param quiet \code{FALSE} if status updates are desired, \code{TRUE} otherwise.
#'
#' @return a \code{data.frame} of photo EXIF information.
#'
#' @examples
#' files <- list.files(path.package("exifr"), recursive=TRUE, pattern="*.jpg", full.names=TRUE)
#' exifinfo <- exifr(files)
#'
#' @export
#'
exifr <- function(filename, quiet=FALSE) {
  fnames <- NULL ; rm(fnames); i <-NULL; rm(i); command <- NULL; rm(command)

  if(length(filename) == 0) {
    return(data.frame())
  }

  foreach <- foreach::foreach
  `%do%` <- foreach::`%do%`

  if(.Platform$OS.type == "windows") {
    commandlength <- 8191 #according to https://support.microsoft.com/en-us/kb/830473
  } else {
    #according to the interweb this should be around 100kb, but 50kb should do
    #(is 'getconf ARG_MAX' on mac, equals 262144)
    commandlength <- 50*1024
  }

  if(!quiet) message("Generating command line arguments...")

  filenameslist <- list(filename)
  nominallen <- length(filename)
  commands <- foreach(fnames=filenameslist, .combine=c) %do% {exiftool.command(args=c("-n", "-csv"), fnames)}
  while(any(nchar(commands) >= commandlength) && commandlength != 0 && nominallen >= 2) {
    #subdivide files until all commands are less than commandlength
    nominallen <- as.integer(nominallen / 2)
    if((length(filename) %% nominallen) == 0) {
      ngroups = length(filename) / nominallen
    } else {
      ngroups <- as.integer(length(filename)/nominallen) + 1
    }
    filenameslist <- foreach(i=1:ngroups) %do% {
      minind <- ((i-1)*nominallen+1)
      maxind <- min(i*nominallen, length(filename))
      filename[minind:maxind]
    }
    commands <- foreach(fnames=filenameslist, .combine=c) %do% {exiftool.command(args=c("-n", "-csv"), fnames)}
  }

  if(!quiet) message("Running ", length(commands), " commands")
  return(foreach(command=commands, .combine=plyr::rbind.fill, .multicombine=TRUE) %do% {
    if(!quiet) message(command)
    read.csv(textConnection(system(command, intern=TRUE, ignore.stderr = quiet)), stringsAsFactors = FALSE)
  })
}

#' Call exiftool from R
#'
#' @param fnames a list of filenames (\code{shQuote()} will be applied to this vector)
#' @param args a list of non-shell quoted arguments (e.g. \code{-n -csv})
#'
#' @return the output generated by exiftool.
#' @export
#'
#' @examples
#' exiftool.call()
#'
exiftool.call <- function(fnames=NULL, args=c("--help")) {
  system(exiftool.command(args, fnames), intern = TRUE)
}

exiftool.command <- function(args, fnames) {
  exiftoolpath <- file.path(path.package("exifr"), "exiftool/exiftool.pl")
  paste("perl", shQuote(exiftoolpath), paste(args, collapse=" "), paste(shQuote(fnames), collapse=" "))
}
