
#' Read EXIF data
#'
#' This function has been deprecated, use \link{read_exif} instead.
#'
#' @param filename A vector of filenames (like that generated by
#'   \code{list.files(..., full.names=TRUE)})
#' @param recursive If directory is specified by \code{filename}, process files recursively.
#' @param quiet \code{FALSE} if status updates are desired, \code{TRUE}
#'   otherwise.
#' @param exiftoolargs a list of args to be passed to ExifTool (e.g. \code{c("-filename", "-imagesize")})
#'
#' @export
#'
exifr <- function(filename, recursive=FALSE, quiet=TRUE, exiftoolargs=NULL) {
  message("exifr() is deprecated, and has been replaced by read_exif()")
  fnames <- NULL ; rm(fnames); i <-NULL; rm(i); command <- NULL; rm(command)

  if(length(filename) == 0) {
    return(data.frame())
  }

  if(recursive) {
    exiftoolargs <- c(exiftoolargs, "-r")
  }

  foreach <- foreach::foreach
  `%do%` <- foreach::`%do%`

  if(.Platform$OS.type == "windows") {
    commandlength <- 8191 #according to https://support.microsoft.com/en-us/kb/830473
  } else {
    #according to the interweb this should be around 100kb, but 50kb should do
    #(is 'getconf ARG_MAX' on mac, equals 262144)
    commandlength <- 50*1024
  }

  message("Generating command line arguments...")

  filenameslist <- list(filename)
  nominallen <- length(filename)
  commands <- foreach(fnames=filenameslist, .combine=c) %do% {
    exiftool.command(args=c("-n", "-csv", "-q", exiftoolargs), fnames)
  }
  while(any(nchar(commands) >= commandlength) && commandlength != 0 && nominallen >= 2) {
    #subdivide files until all commands are less than commandlength
    nominallen <- as.integer(nominallen / 2)
    if((length(filename) %% nominallen) == 0) {
      ngroups = length(filename) / nominallen
    } else {
      ngroups <- as.integer(length(filename)/nominallen) + 1
    }
    filenameslist <- foreach(i=1:ngroups) %do% {
      minind <- ((i-1)*nominallen+1)
      maxind <- min(i*nominallen, length(filename))
      filename[minind:maxind]
    }
    commands <- foreach(fnames=filenameslist, .combine=c) %do% {
      exiftool.command(args=c("-n", "-csv", "-q", exiftoolargs), fnames)
    }
  }

  message("Running ", length(commands), " commands")
  return(foreach(command=commands, .combine=plyr::rbind.fill, .multicombine=TRUE) %do% {
    if(!quiet) message(command)
    if(quiet) {
      suppressMessages(suppressWarnings({
        utils::read.csv(textConnection(system(command, intern=TRUE, ignore.stderr = TRUE)), stringsAsFactors = FALSE)
      }))
    } else {
      utils::read.csv(textConnection(system(command, intern=TRUE, ignore.stderr = TRUE)), stringsAsFactors = FALSE)
    }
  })
}

#' Call exiftool from R
#'
#' This function has been deprecated. Use \link{exiftool_call} instead.
#'
#' @param args a list of non-shell quoted arguments (e.g. \code{-n -csv})
#' @param fnames a list of filenames (\code{shQuote()} will be applied to this vector)
#' @param intern \code{TRUE} if output should be returned as a character vector.
#' @param ... additional arguments to be passed to \code{system()}
#'
#' @export
#'
exiftool.call <- function(args=c("--help"), fnames=NULL, intern=FALSE, ...) {
  message("exiftool.call has been deprecated and has been replaced by exiftool_call()")
  system(exiftool.command(args, fnames), intern=intern, ...)
}


# private helper command
exiftool.command <- function(args, fnames) {
  exiftoolpath <- options("exifr.exiftoolcommand")$exifr.exiftoolcommand
  if(is.null(exiftoolpath)) stop("ExifTool not properly installed")
  if(length(fnames) > 0) {
    paste(exiftoolpath, paste(args, collapse=" "), paste(shQuote(fnames), collapse=" "))
  } else {
    paste(exiftoolpath, paste(args, collapse=" "))
  }
}
